parameters:
#    rebase_bigv.example.class: Rebase\BigvBundle\Example

services:
#    rebase_bigv.example:
#        class: %rebase_bigv.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
