security:
    encoders:
        Rebase\UserBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
            
    providers:
        administrators:
            entity: { class: RebaseUserBundle:User, property: email }

    firewalls:
        secured_area:
            pattern:    ^/fm
            anonymous: ~
            form_login:
              login_path:  /fm/login
              check_path:  /fm/login_check
              
    access_control:
      - { path: ^/fm/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/fm/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/fm, roles: ROLE_USER }
